[package]
name = "LIMLA"
version = "0.1.0"
edition = "2024"
author = "Victor Cerqueira"

[dependencies]
image = { version = "0.24", features = ["jpeg"] }
glob = "0.3.3"
indicatif = "0.18.3"
rayon = "1.11.0"
